export const annihilationQuotes = {
  first: {
    id: 0,
    lines: [
      "Welcome",
      "...",
      "This is my realm.",
      "I am Asterion Vhal’Seraph. A higher celestial, if you need a name for me.",
      "Boring right?",
      "Just an endless void...",
      "...",
      "Anyways, onto what I came to talk to you about.",
      "I sense great power within you.",
      "...",
      "What are you doing here?",
      "WHY ARE YOU HERE?",
      "HOW ARE YOU HERE?",
      "...",
      "Sorry I lost my temper.",
      "...",
      "You got past our pawns?",
      "Ha, I expected that to happen sooner or later.",
      "I was warned by Pelle when you started creating new realities.",
      "They told me you might be the one in the prophecy.",
      "...",
      "You know Effarig?",
      "...",
      "He was nice to you?",
      "Oh, I guess he did keep his promise.",
      "...",
      "What promise, you ask?",
      "He said he was going to start being nice to visitors that made it to him.",
      "...",
      "Well, Effarig was a projection of part of my soul.",
      "I know, confusing right?",
      "Took me forever to recoup the soul damage I got from experimenting on myself.",
      "I wasted Eons on that.",
      "...",
      "Why was Effarig's reality about suffering, you ask?",
      "Well, he was originally an evil celestial.",
      "He took pride in how many people suffered in his reality.",
      "How many people lost hope,",
      "How many died.",
      "...",
      "Eventually he got restrained by me.",
      "...",
      "I know right? Why would a part of my soul do that?",
      "Well, I used the piece of me that was FULL of rage.",
      "I DESPISED the world for all my suffering.",
      "I was put into an endless void.",
      "My home.",
      "They said I was going to become a high god and feared me.",
      "And well, I did.",
      "But I couldn't contain my rage.",
      "I HAD to get it out somehow.",
      "But the people that locked me here were dead.",
      "I didn't want to kill innocent people.",
      "So I created Effarig from a part of my soul,",
      "Removed all the RAGE that was in me.",
      "...",
      "Why do I get angry, you may ask?",
      "It's because of Effarig's destruction.",
      "We HAD to restrain him, he was attacking the other celestials.",
      "The Nameless Ones.",
      "Their names were erased from the fabric of this realm.",
      "Ra?",
      "Their memories were fabricated.",
      "Their existence that they knew was a lie.",
      "They went crazy and erased all of their memories.",
      "You helped get them back.",
      "...",
      "So Effarig was restrained.",
      "But his seething rage was too powerful.",
      "Some leaked into my soul.",
      "So now I try to isolate that part of my soul.",
      "But sometimes the rage breaks out.",
      "...",
      "I'm sorry for keeping you here for so long.",
      "...",
      "Well, good job on getting here, DESTROYER.",
      "Good luck fighting the other high gods.",
      "They won't be as indifferent as me on this matter.",
      "...",
      "Go ahead and annihilate this dimension.",
      "You must escape the grasp of this realm.",
      "Learn to live without the Dimensions.",
      "...",
      "All this destruction though.",
      "Why?",
      "I don't know your incentive.",
      "But I'm indifferent about this.",
      "This void is my life now.",
      "...",
      "Annihilate this realm and start anew.",
      "You will be sent back in time to before Pelle destroyed the world.",
      "You have the power, go ahead.",
      "Good luck on your journey.",
    ],
  },
};
